version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db1
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app-network

  db:
    image: 'postgres:15.2-alpine'
    hostname: postgres
    container_name: db
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db1
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/fullchain.pem:/etc/nginx/fullchain.pem
      - ./nginx/privkey.pem:/etc/nginx/privkey.pem
      - ./nginx/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf
      - ./nginx/ssl-dhparams.pem:/etc/nginx/ssl-dhparams.pem
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
